// sopc_scope_sys_pin_sharer.v

// This file was auto-generated from altera_tristate_conduit_pin_sharer_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 13.1 162 at 2014.06.12.13:40:04

`timescale 1 ps / 1 ps
module sopc_scope_sys_pin_sharer (
		input  wire        clk_clk,                   //   clk.clk
		input  wire        reset_reset,               // reset.reset
		output wire        request,                   //   tcm.request
		input  wire        grant,                     //      .grant
		output wire [19:0] vram_tcm_address_out,      //      .vram_tcm_address_out_out
		input  wire [0:0]  vram_tcm_waitrequest_in,   //      .vram_tcm_waitrequest_in_in
		output wire [0:0]  vram_tcm_chipselect_n_out, //      .vram_tcm_chipselect_n_out_out
		output wire [0:0]  rom_tcm_read_out,          //      .rom_tcm_read_out_out
		output wire [0:0]  rom_tcm_chipselect_n_out,  //      .rom_tcm_chipselect_n_out_out
		output wire [0:0]  ram_tcm_read_out,          //      .ram_tcm_read_out_out
		output wire [0:0]  ram_tcm_chipselect_n_out,  //      .ram_tcm_chipselect_n_out_out
		output wire [18:0] addr,                      //      .addr_out
		output wire [0:0]  we,                        //      .we_out
		output wire [31:0] data,                      //      .data_out
		input  wire [31:0] data_in,                   //      .data_in
		output wire        data_outen,                //      .data_outen
		input  wire        tcs0_request,              //  tcs0.request
		output wire        tcs0_grant,                //      .grant
		input  wire [16:0] tcs0_address_out,          //      .address_out
		input  wire [0:0]  tcs0_write_n_out,          //      .write_n_out
		input  wire [0:0]  tcs0_read_out,             //      .read_out
		input  wire [7:0]  tcs0_data_out,             //      .data_out
		output wire [7:0]  tcs0_data_in,              //      .data_in
		input  wire        tcs0_data_outen,           //      .data_outen
		input  wire [0:0]  tcs0_chipselect_n_out,     //      .chipselect_n_out
		input  wire        tcs1_request,              //  tcs1.request
		output wire        tcs1_grant,                //      .grant
		input  wire [18:0] tcs1_address_out,          //      .address_out
		input  wire [0:0]  tcs1_read_out,             //      .read_out
		input  wire [7:0]  tcs1_data_out,             //      .data_out
		output wire [7:0]  tcs1_data_in,              //      .data_in
		input  wire        tcs1_data_outen,           //      .data_outen
		input  wire [0:0]  tcs1_chipselect_n_out,     //      .chipselect_n_out
		input  wire        tcs2_request,              //  tcs2.request
		output wire        tcs2_grant,                //      .grant
		input  wire [19:0] tcs2_address_out,          //      .address_out
		output wire [0:0]  tcs2_waitrequest_in,       //      .waitrequest_in
		input  wire [0:0]  tcs2_write_n_out,          //      .write_n_out
		input  wire [31:0] tcs2_data_out,             //      .data_out
		output wire [31:0] tcs2_data_in,              //      .data_in
		input  wire        tcs2_data_outen,           //      .data_outen
		input  wire [0:0]  tcs2_chipselect_n_out      //      .chipselect_n_out
	);

	wire  [2:0] arbiter_grant_data;        // arbiter:next_grant -> pin_sharer:next_grant
	wire        arbiter_grant_ready;       // pin_sharer:ack -> arbiter:ack
	wire        pin_sharer_tcs2_arb_valid; // pin_sharer:arb_vram_tcm -> arbiter:sink2_valid
	wire        pin_sharer_tcs1_arb_valid; // pin_sharer:arb_rom_tcm -> arbiter:sink1_valid
	wire        pin_sharer_tcs0_arb_valid; // pin_sharer:arb_ram_tcm -> arbiter:sink0_valid

	sopc_scope_sys_pin_sharer_pin_sharer pin_sharer (
		.clk                       (clk_clk),                   //      clk.clk
		.reset                     (reset_reset),               //    reset.reset
		.request                   (request),                   //      tcm.request
		.grant                     (grant),                     //         .grant
		.vram_tcm_address_out      (vram_tcm_address_out),      //         .vram_tcm_address_out_out
		.vram_tcm_waitrequest_in   (vram_tcm_waitrequest_in),   //         .vram_tcm_waitrequest_in_in
		.vram_tcm_chipselect_n_out (vram_tcm_chipselect_n_out), //         .vram_tcm_chipselect_n_out_out
		.rom_tcm_read_out          (rom_tcm_read_out),          //         .rom_tcm_read_out_out
		.rom_tcm_chipselect_n_out  (rom_tcm_chipselect_n_out),  //         .rom_tcm_chipselect_n_out_out
		.ram_tcm_read_out          (ram_tcm_read_out),          //         .ram_tcm_read_out_out
		.ram_tcm_chipselect_n_out  (ram_tcm_chipselect_n_out),  //         .ram_tcm_chipselect_n_out_out
		.addr                      (addr),                      //         .addr_out
		.we                        (we),                        //         .we_out
		.data                      (data),                      //         .data_out
		.data_in                   (data_in),                   //         .data_in
		.data_outen                (data_outen),                //         .data_outen
		.tcs0_request              (tcs0_request),              //     tcs0.request
		.tcs0_grant                (tcs0_grant),                //         .grant
		.tcs0_tcm_address_out      (tcs0_address_out),          //         .address_out
		.tcs0_tcm_write_n_out      (tcs0_write_n_out),          //         .write_n_out
		.tcs0_tcm_read_out         (tcs0_read_out),             //         .read_out
		.tcs0_tcm_data_out         (tcs0_data_out),             //         .data_out
		.tcs0_tcm_data_in          (tcs0_data_in),              //         .data_in
		.tcs0_tcm_data_outen       (tcs0_data_outen),           //         .data_outen
		.tcs0_tcm_chipselect_n_out (tcs0_chipselect_n_out),     //         .chipselect_n_out
		.tcs1_request              (tcs1_request),              //     tcs1.request
		.tcs1_grant                (tcs1_grant),                //         .grant
		.tcs1_tcm_address_out      (tcs1_address_out),          //         .address_out
		.tcs1_tcm_read_out         (tcs1_read_out),             //         .read_out
		.tcs1_tcm_data_out         (tcs1_data_out),             //         .data_out
		.tcs1_tcm_data_in          (tcs1_data_in),              //         .data_in
		.tcs1_tcm_data_outen       (tcs1_data_outen),           //         .data_outen
		.tcs1_tcm_chipselect_n_out (tcs1_chipselect_n_out),     //         .chipselect_n_out
		.tcs2_request              (tcs2_request),              //     tcs2.request
		.tcs2_grant                (tcs2_grant),                //         .grant
		.tcs2_tcm_address_out      (tcs2_address_out),          //         .address_out
		.tcs2_tcm_waitrequest_in   (tcs2_waitrequest_in),       //         .waitrequest_in
		.tcs2_tcm_write_n_out      (tcs2_write_n_out),          //         .write_n_out
		.tcs2_tcm_data_out         (tcs2_data_out),             //         .data_out
		.tcs2_tcm_data_in          (tcs2_data_in),              //         .data_in
		.tcs2_tcm_data_outen       (tcs2_data_outen),           //         .data_outen
		.tcs2_tcm_chipselect_n_out (tcs2_chipselect_n_out),     //         .chipselect_n_out
		.ack                       (arbiter_grant_ready),       //    grant.ready
		.next_grant                (arbiter_grant_data),        //         .data
		.arb_vram_tcm              (pin_sharer_tcs2_arb_valid), // tcs2_arb.valid
		.arb_rom_tcm               (pin_sharer_tcs1_arb_valid), // tcs1_arb.valid
		.arb_ram_tcm               (pin_sharer_tcs0_arb_valid)  // tcs0_arb.valid
	);

	sopc_scope_sys_pin_sharer_arbiter arbiter (
		.clk         (clk_clk),                   //       clk.clk
		.reset       (reset_reset),               // clk_reset.reset
		.ack         (arbiter_grant_ready),       //     grant.ready
		.next_grant  (arbiter_grant_data),        //          .data
		.sink0_valid (pin_sharer_tcs0_arb_valid), //     sink0.valid
		.sink1_valid (pin_sharer_tcs1_arb_valid), //     sink1.valid
		.sink2_valid (pin_sharer_tcs2_arb_valid)  //     sink2.valid
	);

endmodule
